name: eak_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  google_maps_flutter: ^2.14.0

  # Camera & Image
  camera: ^0.11.0
  image_picker: ^1.1.1

  # Splash & launcher icons
  image: ^4.0.15

  # --- MACHINE LEARNING (TFLITE) ---
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70

  google_mlkit_face_detection: ^0.12.0

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^1.2.1

  # Date & Time
  intl: ^0.20.2

  # URL Launcher
  url_launcher: ^6.2.3
  
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  camera: ^0.11.0
  image: ^4.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/splashScreen/
    - assets/onboarding/
    - assets/icon_login.png
